# Generated by Django 5.0.4 on 2024-05-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0003_registerdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdb',
            name='Image',
        ),
    ]
