# Generated by Django 5.0.4 on 2024-06-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0006_checkdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='checkdb',
            new_name='paymentdb',
        ),
    ]
