# Generated by Django 5.0.4 on 2024-06-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0007_rename_checkdb_paymentdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdb',
            name='Total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
